### ISSUE TITLE
Mode: curated "crisis locations"

### ISSUE THREAD

**Issue by marktani** [climate-phoenix/map#10]
Amazon rainforest fire is happening right now -> there is a hashtag connected with this, we can connect it with a Twitter feed for example

**Comment by marktani** [comment]
This looks like a cool example for crisis locations, @divyenduz! 

https://docs.mapbox.com/mapbox-gl-js/example/add-image-animated/

**Comment by marktani** [comment]
also, this: https://uber.github.io/react-map-gl/#/Documentation/api-reference/popup

**Comment by divyenduz** [comment]
Amazon fires 

--- 

Meta: Big orgs

- https://climate.nasa.gov/
- https://climate.nasa.gov/evidence/
- [NASA's AIRS Maps Carbon Monoxide from Brazil Fires](https://climate.nasa.gov/news/2907/nasas-airs-maps-carbon-monoxide-from-brazil-fires/)
- https://climate.nasa.gov/news/2902/nasa-studies-how-arctic-wildfires-change-the-world/
- https://www.un.org/en/climatechange/

**Comment by divyenduz** [comment]
Done in some capacity: https://map-izgt8qww0.now.sh/
