### ISSUE TITLE
App logo

### ISSUE THREAD

**Issue by marktani** [climate-phoenix/map#11]

**Comment by yuvikakoul** [comment]
Adding a logo design proposal
![climate-phoenix-logo](https://user-images.githubusercontent.com/9837123/63649741-1d5d8700-c75f-11e9-90a7-0cf7ef7e2553.jpg)
The idea is to show a phoenix securing the water bubble representing climate.

**Comment by yuvikakoul** [comment]
Adding the size variations and logo assets.
[Climate_Phoenix_Logo.zip](https://github.com/climate-phoenix/map/files/3549341/Climate_Phoenix_Logo.zip)

**Comment by divyenduz** [comment]
Thank you 🙌
